# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86e55331be34a5b601eaf7a1a0bd36fdfe76ba7cd6863f0ca5b0abcfd9924b8f11f8d10ff3c9cad90bf0dec60c438e6a3a0eee78cd42c5fe7cdc968cf1f26d9b

test:
  secret_key_base: a72ada45146d03f283944a7846ca3e1e02cbfa84d9b35bbce79bc03e73cf7c9b2bb370ae00b5634d063894a1052b419cfbec21217541f2ff5b4230f733afd5ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
